# chocolate-doom-setup
# Autogenerated from man page /usr/share/man/man6/chocolate-doom-setup.6.gz
complete -c chocolate-doom-setup -o config --description 'Load configuration from the specified file, instead of default. cfg.'
complete -c chocolate-doom-setup -o extraconfig --description 'Load extra configuration from the specified file, instead of chocolate-doom.'


