# chocolate-server
# Autogenerated from man page /usr/share/man/man6/chocolate-server.6.gz
complete -c chocolate-server -o ignoreversion --description 'Ignore version mismatches between the server and the client.'
complete -c chocolate-server -o port --description 'Use the specified UDP port for communications, instead of the default (2342).'
complete -c chocolate-server -o privateserver --description 'Don\'t register with the global master server.'
complete -c chocolate-server -o servername --description 'Specify a name for the server.'


