# prboom-plus-game-server
# Autogenerated from man page /usr/share/man/man6/prboom-plus-game-server.6.gz
complete -c prboom-plus-game-server -s N --description 'Specifies the number of players in the game (default 2).'
complete -c prboom-plus-game-server -s e --description 'The episode to play (default 1).'
complete -c prboom-plus-game-server -s l --description 'The level to play (default 1).'
complete -c prboom-plus-game-server -s s --description 'Specify the skill level to play (1-5).'
complete -c prboom-plus-game-server -s d --description 'Set game mode to (old) deathmatch (default is cooperative).'
complete -c prboom-plus-game-server -s a --description 'Set game mode to `altdeath\' (v2 deathmatch) (default is cooperative).'
complete -c prboom-plus-game-server -s f --description 'Select fast mode (monsters move faster).'
complete -c prboom-plus-game-server -s n --description 'Selects nomonsters mode, i. e.  there are no monsters in the game.'
complete -c prboom-plus-game-server -s r --description 'Respawn mode.  If you don\'t know what this is, you don\'t want to ;-).'
complete -c prboom-plus-game-server -s c --description 'Specifies a configuration file to read which sets parameters for the game.'
complete -c prboom-plus-game-server -s w --description 'Specifies a WAD file to play.'
complete -c prboom-plus-game-server -s t --description 'Reserved.'
complete -c prboom-plus-game-server -s x --description 'This causes extra information to be sent with each network packet; this  will…'
complete -c prboom-plus-game-server -s p --description 'Tells  prboom-game-server what port number to communicate via (default 5030).'
complete -c prboom-plus-game-server -s v --description 'Increases verbosity level; causes more diagnostics to be printed, the more  t…'


