@startuml

skinparam monochrome true
skinparam shadowing false

actor User
agent Browser
package "Application" {
    agent Model
    agent View
    agent Controller
}
package "Data" {
    artifact "JSON files" as JSON
    agent "Data Generation Scripts" as Scripts
}

User -right-> Browser
Browser -up-> View

View <-> Controller
Model <-> Controller

Scripts -right-> JSON
JSON -up-> Model

@enduml
